開発環境を整えてトップページを作成した
gKokasai/23rd.kokasai.com pull request #128
Opened 2021-10-06 07:32 UTC by axelaspor2

2021-10-06 22:00 UTC, sya-ri requested changes
遅れて申し訳ないです。何個か変更して欲しいとこあるのでお願いします

2021-10-06 22:00 UTC, sya-ri commented on package.json
> +    "axios": "^0.21.4",
axios 使っていないような気がします。使わないなら削除しておいて良いと思います

2021-10-06 22:00 UTC, sya-ri commented on src/components/project/Project.tsx
> +const Project: React.FC = () => <>project</>;
今後実装予定なら TODO コメントが欲しいです

2021-10-06 22:00 UTC, sya-ri commented on src/components/top/left/Left.tsx
> +          <a href="/">
map を使うなら key prop を設定してください

2021-10-06 22:00 UTC, sya-ri commented on src/components/common/Footer.tsx
> +              <a href="/">
map を使うなら key prop を設定してください

2021-10-06 22:00 UTC, sya-ri commented on src/components/top/right/Right.tsx
> +            href="https://Instagram.com"
インスタのURLがプロフィールじゃないですよ

2021-10-06 22:00 UTC, sya-ri commented on src/components/top/right/Right.tsx
> +            href="https://twitter.com"
TwitterのURLがプロフィールじゃないですよ

2021-10-06 22:00 UTC, sya-ri commented on src/components/common/Header.tsx
> +        <a href="https://Instagram.com/nitgc_kokasai">
外部リンクは定数化しておいた方がいいと思います

2021-10-06 22:00 UTC, sya-ri commented on src/components/common/Footer.tsx
> +              <a href="/">
仮のリンクなのであればTODOコメントをつけておいてください。

2021-10-06 22:00 UTC, sya-ri commented on src/components/common/Footer.tsx
> +          <a href="/">
仮のリンクなのであれば、TODOコメントをつけておいてください。ですが、別の場所にリンク定義してそれを定数として使う方が変更に強いと思います

2021-10-07 04:17 UTC, sya-ri requested changes
レビュー漏れです。また、レビューされた内容を修正した場合はコミット分けしておいてください。フォースプッシュする場合はレビュー待ちの時だけにしてください(誰も見ていないだろうと考えられる場合にはコミットをまとめた方がわかりやすいです)

2021-10-07 04:17 UTC, sya-ri commented on package.json
> +    "js-base64": "^3.7.2",
なんのためのライブラリですか？

2021-10-07 04:49 UTC, sya-ri commented
作業したい時はタイトルに WIP をつけるのではなく、Draft PR にするといいです

2021-10-07 04:50 UTC, cheichey commented
わかりました

2021-10-07 07:09 UTC, cheichey commented
確認お願いします

2021-10-07 07:11 UTC, sya-ri approved these changes
よさそうです☺️

2021-10-07 07:12 UTC, merged