企画一覧ページの作成
gKokasai/23rd.kokasai.com pull request #131
Opened 2021-10-10 13:39 UTC by axelaspor2

2021-10-11 08:22 UTC, axelaspor2 commented
jsonファイルの読み込みの確認をしました。

2021-10-12 06:35 UTC, cheichey commented
#132

2021-10-16 06:59 UTC, cheichey commented
スタイル、地図から探す以外は実装が終わりました。
Adobeのソフトがまだ使えないので、使えるようになったら別のPRで開発を再開します。
他のページを実装したいのですが、このPRのコミットが元となることも多いのでとりあえずマージしたいです。

2021-10-16 11:34 UTC, sya-ri requested changes
見てて思った改善点です。対応お願いします。

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/WithHeaderHoverCard.tsx
> +      <div className="text-2xl">{header}</div>
![image](https://user-images.githubusercontent.com/34268371/137584860-9884abbd-19d6-49a7-ad3a-1d434d81485c.png)

ホバーカードのサイズが小さくて文字寄せが左になってしまうので、 `text-center` をつけた方がいいと思います。

また、横に padding があった方が綺麗だと思うので、`px-2` や `px-1` をつけた方がいいと思います。

```suggestion
      <div className="text-2xl text-center px-2">{header}</div>
```

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/group/list/FilterLabel.tsx
> +const FilterLabel: React.FC<LabelProps> = (props) => {
![image](https://user-images.githubusercontent.com/34268371/137585049-8d5d7c52-bce7-43e6-89f6-e697b2425e08.png)

- 数字と文字の高さがズレているのが気になります。
- １つでも選択したらそれ以外が解除される仕様はUXとしてよくないと思います。
  - 実装が厳しいのであれば、選択を解除して全表示に切り替えられるようにしてほしいです。

2021-10-16 11:34 UTC, sya-ri commented on src/components/common/Footer.tsx
>                // TODO: 各ページ実装後、仮リンクではなく実装する
```suggestion
```
TODO は消してください

2021-10-16 11:34 UTC, sya-ri commented on src/components/common/Header.tsx
>                // TODO: 各ページ実装後、仮リンクではなく実装する
```suggestion
```

TODO は削除してください

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/Project.tsx
>  // TODO: 企画一覧ページの作成
```suggestion
```

TODO は削除してください

2021-10-16 11:34 UTC, sya-ri commented on src/components/App.tsx
>  const App: React.FC = () => (
![image](https://user-images.githubusercontent.com/34268371/137585500-35e1418e-b313-4e0f-a2f7-bba3a3e568d3.png)

一定以下のスクリーン幅にするとスタイルが崩壊します。全画面表示以外も想定してください

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/group/list/ProjectList.tsx
> +const ProjectList: React.FC<ProjectListProps> = (props) => {
![image](https://user-images.githubusercontent.com/34268371/137585583-55c8a22e-e77d-47a5-af5a-5f5f70906187.png)

クラス順にソートしてほしいです。(1,2,3,4,5 / M,E,J,K,C)

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/group/list/FilterLabel.tsx
> +const FilterLabel: React.FC<LabelProps> = (props) => {
![image](https://user-images.githubusercontent.com/34268371/137585636-1a4dcddf-88d9-4070-9a5f-b65886baa0e6.png)

ボタンを押した時にフィルター情報をクエリに格納するようにしてほしいです。ページバック対策・共有目的

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/detail/ProjectDetail.tsx
> +            <GroupOutlinedIcon />
![image](https://user-images.githubusercontent.com/34268371/137585699-ba0305e1-0ae1-4b98-a434-e2738dddcb81.png)

アイコンと団体名の間に 1, 2 程度の padding がほしいです

2021-10-16 11:34 UTC, sya-ri commented on src/components/project/detail/ProjectDetail.tsx
> +          <div className="border-greenC7D1BD border-2">
![image](https://user-images.githubusercontent.com/34268371/137585767-be9a2988-2f4a-4d6b-ab3a-f1e6b2d6ec4a.png)

こういったことがあるので、ボーダーはいらないと思います

2021-10-17 08:14 UTC, axelaspor2 commented on src/components/project/group/list/FilterLabel.tsx
> +const FilterLabel: React.FC<LabelProps> = (props) => {
> - 数字と文字の高さがズレているのが気になります。

フォントの問題なので、渡辺くんと話し合ってフォントを決めようと思います

2021-10-17 08:15 UTC, cheichey commented
指摘いただいた点の修正をしました
よろしくお願いします

2021-10-17 09:43 UTC, sya-ri commented on src/components/project/group/list/FilterLabel.tsx
> +const FilterLabel: React.FC<LabelProps> = (props) => {
@cheichey 

![image](https://user-images.githubusercontent.com/34268371/137621567-cc0f15eb-6dc4-4b56-8706-a63d77f0d4ba.png)

`%20` が入ってるのは気持ち悪く見えます。けしてください

2021-10-17 09:47 UTC, sya-ri requested changes
一箇所だけ追加修正をお願いします。解決済みになっているものについては大丈夫です

2021-10-17 10:11 UTC, axelaspor2 commented on src/components/project/group/list/FilterLabel.tsx
> +const FilterLabel: React.FC<LabelProps> = (props) => {
GetURIに入る文字列は、エンコードされるのですが、そのときにスペース文字は `%20` または `+` にエンコードされるみたいでこれを変えることはできません。
なので、`4, 5年` ではなく `4,5年`　とする方針にします

2021-10-17 10:24 UTC, sya-ri approved these changes
修正ありがとうございます :+1:

2021-10-17 11:37 UTC, merged