feat: アクセスページを作成した
gKokasai/23rd.kokasai.com pull request #146
Opened 2021-10-18 05:16 UTC by axelaspor2

2021-10-18 06:04 UTC, sya-ri requested changes
### [Want] "または" を目だなくして欲しい。

![image](https://user-images.githubusercontent.com/34268371/137676271-3ac4a79e-292d-4c7f-8c77-bc6b33493cdc.png)

"徒歩30分" と "または" と "タクシー10分" という情報が同列になっているので少しわかりにくいような気がします

- > **徒歩30分** または **タクシー10分**

  "または" の前後に空白を入れたり、文字幅や文字サイズを変えてみてください。良いと思ったものを採用していただければ結構です
---

### [Must] バスの案内がわかりにくい

![image](https://user-images.githubusercontent.com/34268371/137676935-ccbc6680-7154-4c2d-a154-5575ef8f6fba.png)

```
井野駅北バス停
  ↓
市内循環バス「ぐるりん」大八木線・中尾先回り（系統番号6）
  ↓
群馬高専前（約20分）
```

のように矢印を使ってわかりやすくしてほしいです

---

### [Must] 選択肢っぽくない

![image](https://user-images.githubusercontent.com/34268371/137676958-451564fe-7907-4a15-a27b-443ffc9b5dfd.png)

 List を使った方がいいと思います

---

### [Must] 下部に padding が欲しい

![image](https://user-images.githubusercontent.com/34268371/137677206-841f57af-dc99-43d0-b75d-5ee41008ef17.png)

きもいですよね

2021-10-19 03:55 UTC, cheichey commented
修正しました。
よろしくお願いします

2021-10-19 05:53 UTC, sya-ri reviewed
一箇所、修正の提案です

2021-10-19 05:53 UTC, sya-ri commented on src/components/common/Paragraph.tsx
> +  <p className="pc:text-lg desktop:text-xl pl-10 pt-3 pr-4 pc:pl-20 pc:pt-5 pc:pr-8">{children}</p>
![image](https://user-images.githubusercontent.com/34268371/137851335-f1859223-87f8-4147-84cc-527f88569b1d.png)

モバイルで左側のpaddingが多いのが気になります。左右で揃えてしまっていい気がします

```suggestion
  <p className="pc:text-lg desktop:text-xl px-4 pt-3 pc:pl-20 pc:pt-5 pc:pr-8">{children}</p>
</p>
```

2021-10-19 05:55 UTC, sya-ri approved these changes
対応ありがとうございます

2021-10-19 07:10 UTC, merged