feat: タイムテーブルページを作成した
gKokasai/23rd.kokasai.com pull request #159
Opened 2021-10-20 13:23 UTC by axelaspor2

2021-10-20 14:23 UTC, sya-ri requested changes
お昼休憩のアイコンにライセンス表示ありますよ

2021-10-20 22:42 UTC, axelaspor2 commented
いらすとやのイラストに変更しました

2021-10-20 22:49 UTC, sya-ri approved these changes
良いと思います

2021-10-20 23:09 UTC, axelaspor2 commented
すみません、 いくつか修正したのと、ESLintがバグってて効いてなかったので再度確認お願いします。
チェックに追加しておきます

2021-10-21 10:46 UTC, sya-ri approved these changes

2021-10-21 23:43 UTC, merged